test
Building the Rust sidecar under qemu is apparently too expensive and
gets OOM-killed by the runner. It seemed to run fine in previous tests,
but this time, for some reason, I can't manage to make it build.

Signed-off-by: Quentin Monnet <quentin@isovalent.com>

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -13,13 +13,16 @@ jobs:
   build:
     name: Build static retsnoop binary
     runs-on: ubuntu-22.04
-    env:
-      TARGETARCH: ${{ matrix.arch }}
-      FILE_STRING_ARCH_amd64: x86-64
-      FILE_STRING_ARCH_arm64: aarch64
     strategy:
       matrix:
-        arch: [arm64, amd64]
+        include:
+          - arch: amd64
+            file_str: x86-64
+            target: x86_64-unknown-linux-gnu
+
+          - arch: arm64
+            file_str: aarch64
+            target: aarch64-unknown-linux-gnu
 
     steps:
       # amd64 needs the dependencies to build retsnoop
@@ -27,7 +30,7 @@ jobs:
         if: matrix.arch == 'amd64'
         run: |
           sudo apt-get update
-          sudo apt-get install -y cargo llvm libelf-dev
+          sudo apt-get install -y llvm libelf-dev
 
       - name: Checkout retsnoop code
         uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
@@ -35,7 +38,7 @@ jobs:
           submodules: recursive
           path: 'retsnoop'
 
-      - name: Build static retsnoop natively for amd64
+      - name: (amd64) Build static retsnoop natively for amd64
         if: matrix.arch == 'amd64'
         working-directory: 'retsnoop'
         run: |
@@ -43,34 +46,59 @@ jobs:
               make -j -C src V=1
           strip src/retsnoop
 
-      - name: Set up QEMU
+      #- name: (arm64) Pre-compile Rust sidecar binary, addr2line
+      #  if: matrix.arch == 'arm64'
+      #  working-directory: 'retsnoop/src'
+      #  run: |
+      #    rustup target add ${{ matrix.target }}
+      #    # Compiling addr2line itself is supposed to fail at this stage,
+      #    # because we don't have the toolchain for linking with cc/ld. But
+      #    # there doesn't seem to be a way to tell cargo to build the
+      #    # dependencies only. It's still faster to build the deps outside of
+      #    # QEMU, even with the fail attempt on addr2line.
+      #    cargo build --target ${{ matrix.target }} \
+      #        --manifest-path=../sidecar/Cargo.toml --release || true
+
+      - name: (arm64) Set up QEMU
         uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 # v2.1.0
         if: matrix.arch == 'arm64'
         with:
-          platforms: arm64
+          platforms: ${{ matrix.arch }}
 
       # The emulated build leverages Docker and Ubuntu 22.04 container image
       # distribution to have all the needed arm64 packages.
-      - name: Build static retsnoop for arm64 with emulation
+      - name: (arm64) Build static retsnoop for arm64 with emulation
         if: matrix.arch == 'arm64'
-        run:  |
-          docker run --platform linux/arm64 --rm -v $(pwd):/build ubuntu:22.04 \
+        run: |
+          pushd retsnoop/sidecar
+          CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse cargo update --config net.git-fetch-with-cli=true
+          popd
+          docker run --platform linux/arm64 --rm -v $(pwd):/build \
+          -v ${HOME}/.cargo/git:/usr/local/cargo/git \
+          -v ${HOME}/.cargo/registry:/usr/local/cargo/registry \
+          ubuntu:22.04 \
           bash -c "apt-get update && \
-                   apt-get install -y cargo clang llvm make pkg-config gcc \
+                   apt-get install -y cargo clang git llvm make pkg-config gcc \
                        libelf-dev zlib1g-dev && \
                    cd /build/retsnoop && \
+                   pushd sidecar && \
+                   mkdir -p ~/.cargo
+                   echo '[registries.crates-io]' >> ~/.cargo/config.toml
+                   echo 'protocol = \"sparse\"' >> ~/.cargo/config.toml
+                   CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse \
+                   RUST_LOG=cargo::sources=debug cargo update --config net.git-fetch-with-cli=true && \
+                   popd && \
+                   CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse \
                    CFLAGS=--static \
-                       make -j -C src V=1 && \
+                       make -C src V=1 && \
                    strip src/retsnoop"
 
       - name: Test retsnoop binary
         working-directory: 'retsnoop/src'
-        env:
-          ARCH: ${{ env[format('FILE_STRING_ARCH_{0}', matrix.arch)] }}
         run: |
           file ./retsnoop | \
               tee /dev/stderr | \
-              grep -q "${{ env.ARCH }}"
+              grep -q "${{ matrix.file_str }}"
           ./retsnoop --usage | grep -q Usage
           ldd ./retsnoop 2>&1 | \
               tee /dev/stderr | \
